# -*- coding: utf-8 -*-
"""caesars_cipher

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bCDDgFKLLeNd3T7enMP9riiSzHux27N-
"""

#Implement Caesar's cipher 
#Caesar's cipher is essentially an encryption technique
#It uses a 'step' value and increments every letter of a word in the text by that value
#For example if the step value is 2, then "APPLE" becomes "CRRG"
#Write a code which takes input of the step value from the user and the text to be encrypted, and displays the encrypted text