# -*- coding: utf-8 -*-
"""transpose_matrix

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bCDDgFKLLeNd3T7enMP9riiSzHux27N-
"""

#Input an integer array nums and an integer k from the user.
#Return true if there are two distinct indices i and j in the array such that nums[i] == nums[j] and abs(i - j) <= k.