# -*- coding: utf-8 -*-
"""caesars_cipher

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bCDDgFKLLeNd3T7enMP9riiSzHux27N-
"""

#Write a program to determine if a number n input by the user is happy.

#A happy number is a number defined by the following process:

#Starting with any positive integer, replace the number by the sum of the squares of its digits.
#Repeat the process until the number equals 1 (where it will stay), or it loops endlessly in a cycle which does not include 1.
#Those numbers for which this process ends in 1 are happy.
#Print true if n is a happy number, and false if not.