# -*- coding: utf-8 -*-
"""transpose_matrix

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bCDDgFKLLeNd3T7enMP9riiSzHux27N-
"""

#Input two strings s and t from the user, determine if they are isomorphic.

#Two strings s and t are isomorphic if the characters in s can be replaced to get t.

#All occurrences of a character must be replaced with another character while preserving the order of characters. 
#No two characters may map to the same character, but a character may map to itself.