# -*- coding: utf-8 -*-
"""number_complement

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bCDDgFKLLeNd3T7enMP9riiSzHux27N-
"""

#Input two arrays of strings list1 and list2 from the user, find the common strings with the least index sum.
#A common string is a string that appeared in both list1 and list2.
#A common string with the least index sum is a common string such that if it appeared at list1[i] and list2[j] 
#then i + j should be the minimum value among all the other common strings.

#Return all the common strings with the least index sum. Return the answer in any order.