# -*- coding: utf-8 -*-
"""number_complement

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bCDDgFKLLeNd3T7enMP9riiSzHux27N-
"""

#International Morse Code defines a standard encoding where each letter is mapped to a series of dots and dashes, as follows:

#'a' maps to ".-",
#'b' maps to "-...",
#'c' maps to "-.-.", and so on.

#Input a string from user, and print it's Morse Code