# -*- coding: utf-8 -*-
"""number_complement

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bCDDgFKLLeNd3T7enMP9riiSzHux27N-
"""

#Take a number n as input from the user
#Convert n into a binary number
#Take complement of the binary number (convert 1's to 0's and vice versa)
#Convert this number back into decimal number and print it