# -*- coding: utf-8 -*-
"""caesars_cipher

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bCDDgFKLLeNd3T7enMP9riiSzHux27N-
"""

#Pascal's Triangle
#In Pascal's triangle, each number is the sum of the two numbers directly above it
#For example, for 4 rows, the Pascal's triangle would be
#    1
#   1 1
#  1 2 1
# 1 3 3 1
#Take number of rows as input from the user