# -*- coding: utf-8 -*-
"""StudentRecords.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bCDDgFKLLeNd3T7enMP9riiSzHux27N-
"""

#Make a dictionary storing the details of students in a branch
#Input the roll number, name, class, dob of each student from the user
#Store these values in a dictionary using the roll number as keys
#Display the details of each student in the end