# -*- coding: utf-8 -*-
"""number_complement

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bCDDgFKLLeNd3T7enMP9riiSzHux27N-
"""

#Input an m x n matrix from user, return true if the matrix is Toeplitz. Otherwise, return false.

#A matrix is Toeplitz if every diagonal from top-left to bottom-right has the same elements.
#Example of a Toeplitz matrix:
# 1 2 3 4
# 5 1 2 3
# 9 5 1 2