# -*- coding: utf-8 -*-
"""transpose_matrix

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bCDDgFKLLeNd3T7enMP9riiSzHux27N-
"""

#Input a 2D integer array matrix from the user, print the transpose of matrix.

#The transpose of a matrix is the matrix flipped over its main diagonal, switching the matrix's row and column indices.