# -*- coding: utf-8 -*-
"""transpose_matrix

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bCDDgFKLLeNd3T7enMP9riiSzHux27N-
"""

#Input a string s containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid.

#An input string is valid if:

#Open brackets must be closed by the same type of brackets.
#Open brackets must be closed in the correct order.
#Every close bracket has a corresponding open bracket of the same type.